timings = {
    "Monday": {
        "9": None,
        "10": "CC",
        "11": 'CD',
        "12": "AI",
        "13": None,
        "14": "OE",
        "15": None,
        "16": None,
    },
    "Tuesday": {
        "9": None,
        "10": "AI",
        "11": 'CN',
        "12": "CD",
        "13": None,
        "14": "OE",
        "15": None,
        "16": None,
    },
    "Wednesday": {
        "9": None,
        "10": "AI",
        "11": 'CD',
        "12": "CC",
        "13": None,
        "14": "OE",
        "15": None,
        "16": None,
    },
    "Thursday": {
        "9": None,
        "10": "CN",
        "11": 'CD',
        "12": "CC",
        "13": None,
        "14": ["CNLAB", "CDLAB"],
        "15": None,
        "16": None,
    },
    "Friday": {
        "9":  ["CNLAB, CDLAB"],
        "10": None,
        "11": 'CN',
        "12": "CB",
        "13": None,
        "14": None,
        "15": None,
        "16": None,
    },
    "Saturday": None,
    "Sunday": None
}
